# Generated by Django 5.0.6 on 2024-06-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PIDData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('stds_uti_history', models.CharField(max_length=100)),
                ('iud_use', models.CharField(max_length=100)),
                ('past_pelvic_pain', models.CharField(max_length=100)),
                ('imaging_results', models.CharField(max_length=100)),
                ('abnormal_discharge', models.CharField(max_length=100)),
                ('irregular_periods', models.CharField(max_length=100)),
                ('dyspareunia', models.CharField(max_length=100)),
                ('dysuria', models.CharField(max_length=100)),
                ('wbc_count', models.CharField(max_length=100)),
                ('esr', models.CharField(max_length=100)),
                ('crp_level', models.CharField(max_length=100)),
            ],
        ),
    ]
